apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: frontend
  labels:
    app.kubernetes.io/name: frontend
  annotations:
    iam.gke.io/gcp-service-account: gke-frontend@myapp-dev.iam.gserviceaccount.com
