apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
images:
  - name: us-central1-docker.pkg.dev/myapp-dev/myapp-dev-backend/backend
    newTag: REPLACE_GIT_SHA
