apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend
  labels:
    app.kubernetes.io/name: backend
  annotations:
    iam.gke.io/gcp-service-account: gke-backend@myapp-dev.iam.gserviceaccount.com
