apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/namespaces.yaml
  - ../../apps/frontend
  - ../../apps/backend
  - ../../infrastructure/gateway

patches:
  - target:
      kind: Gateway
      name: external-https
    patch: |-
      - op: replace
        path: /metadata/annotations/networking.gke.io~1addresses
        value: myapp-stage-gw-ip
      - op: replace
        path: /metadata/annotations/networking.gke.io~1certmap
        value: myapp-stage-certmap
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: stage.myapp.example.com
  - target:
      kind: ServiceAccount
      name: backend
      namespace: backend
    patch: |-
      - op: replace
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: gke-backend@myapp-stage.iam.gserviceaccount.com
  - target:
      kind: ServiceAccount
      name: frontend
      namespace: frontend
    patch: |-
      - op: replace
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: gke-frontend@myapp-stage.iam.gserviceaccount.com
  - target:
      kind: ExternalSecret
      name: backend-db
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: myapp-stage-db-password
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |-
      - op: replace
        path: /data/DB_HOST
        value: REPLACE_CLOUDSQL_PRIVATE_IP
  - target:
      kind: HorizontalPodAutoscaler
      name: backend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 6

images:
  - name: us-central1-docker.pkg.dev/myapp-dev/myapp-dev-frontend/frontend
    newName: us-central1-docker.pkg.dev/myapp-stage/myapp-stage-frontend/frontend
    newTag: REPLACE_GIT_SHA
  - name: us-central1-docker.pkg.dev/myapp-dev/myapp-dev-backend/backend
    newName: us-central1-docker.pkg.dev/myapp-stage/myapp-stage-backend/backend
    newTag: REPLACE_GIT_SHA
